// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const blogRollPreview: string;
export const left: string;
export const right: string;
export const postWithImage: string;
export const thumbnail: string;
export const date: string;
export const postWithoutImage: string;
export const title: string;
export const readMoreButton: string;
