// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const header: string;
export const thumbnail: string;
export const articles: string;
export const hasThumbnail: string;
export const date: string;
export const extLinkIcon: string;
