// This file is automatically generated. Do not modify this file manually -- YOUR CHANGES WILL BE ERASED!
export const contact: string;
export const inputWrapper: string;
export const submitWrapper: string;
export const captchaWrapper: string;
export const submittedWrapper: string;
export const showlength: string;
